In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.11.0'

In [3]:
a = np.array([1,2,3,4])
b = [4,3,2,1]

In [4]:
t_b = torch.tensor(b)
t_a = torch.from_numpy(a)

In [5]:
print(t_a,t_a.dtype)

tensor([1, 2, 3, 4]) torch.int64


In [6]:
t_b

tensor([4, 3, 2, 1])

In [26]:
torch.randn(3,3)

tensor([[ 0.1287,  0.9771,  0.6867],
        [ 1.1061,  0.8191, -1.4196],
        [-0.4126,  1.2870, -0.6651]])

In [25]:
torch.randn(3,3).to(torch.int64)

tensor([[ 0,  0, -1],
        [-1,  1,  1],
        [-1,  0,  1]])

In [22]:
torch.randint(2,(3,3))

tensor([[0, 1, 0],
        [1, 0, 1],
        [1, 1, 0]])

In [32]:
torch.randint(2,(3,3))

tensor([[1, 1, 0],
        [0, 0, 1],
        [1, 0, 0]])

In [33]:
torch.randint(2,(3,3)).reshape(9)

tensor([0, 1, 0, 1, 0, 1, 0, 1, 1])

In [37]:
torch.randint(2,(3,3)).reshape(1,9)

tensor([[0, 1, 0, 1, 0, 1, 1, 1, 0]])

In [38]:
t1 = torch.rand(2,5)
t2 = torch.normal(mean=0,size=(2,5),std=1)
print(t1)
print(t2)

tensor([[0.6851, 0.4734, 0.2081, 0.6475, 0.9103],
        [0.5071, 0.4719, 0.9436, 0.9313, 0.4932]])
tensor([[ 0.2232,  0.1717, -0.0902,  0.2446,  0.8927],
        [-0.3038,  0.0035,  1.3062,  0.2211,  0.7524]])


In [39]:
torch.multiply(t1,t2)

tensor([[ 0.1529,  0.0813, -0.0188,  0.1584,  0.8127],
        [-0.1540,  0.0016,  1.2326,  0.2059,  0.3711]])

In [45]:
torch.matmul(t1,torch.transpose(t2,0,1))

tensor([[1.1865, 0.8933],
        [0.7772, 1.6571]])

In [47]:
torch.matmul(torch.transpose(t1,0,1),t2)

tensor([[-1.1351e-03,  1.1937e-01,  6.0050e-01,  2.7970e-01,  9.9312e-01],
        [-3.7707e-02,  8.2914e-02,  5.7372e-01,  2.2016e-01,  7.7774e-01],
        [-2.4025e-01,  3.8981e-02,  1.2138e+00,  2.5954e-01,  8.9572e-01],
        [-1.3841e-01,  1.1438e-01,  1.1580e+00,  3.6428e-01,  1.2787e+00],
        [ 5.3342e-02,  1.5800e-01,  5.6210e-01,  3.3174e-01,  1.1838e+00]])

In [50]:
A = torch.ones(3)

In [51]:
B = torch.zeros(3)

In [57]:
torch.cat([A,B])

tensor([1., 1., 1., 0., 0., 0.])

In [58]:
torch.stack([A,B])

tensor([[1., 1., 1.],
        [0., 0., 0.]])