In [1]:
import torch
import numpy as np

In [2]:
from torch.utils.data import DataLoader

In [27]:
a = torch.arange(20)

In [16]:
b = torch.linspace(0,10,10,dtype=torch.float64)

In [17]:
data_loader = DataLoader(b)

In [18]:
for i in data_loader:
    print(i)

tensor([0.], dtype=torch.float64)
tensor([1.1111], dtype=torch.float64)
tensor([2.2222], dtype=torch.float64)
tensor([3.3333], dtype=torch.float64)
tensor([4.4444], dtype=torch.float64)
tensor([5.5556], dtype=torch.float64)
tensor([6.6667], dtype=torch.float64)
tensor([7.7778], dtype=torch.float64)
tensor([8.8889], dtype=torch.float64)
tensor([10.], dtype=torch.float64)


In [28]:
data_loader = DataLoader(a,batch_size=2)

In [30]:
for i,data in enumerate(data_loader):
    print(f"Batch nr. {i}: {data}")

Batch nr. 0: tensor([0, 1])
Batch nr. 1: tensor([2, 3])
Batch nr. 2: tensor([4, 5])
Batch nr. 3: tensor([6, 7])
Batch nr. 4: tensor([8, 9])
Batch nr. 5: tensor([10, 11])
Batch nr. 6: tensor([12, 13])
Batch nr. 7: tensor([14, 15])
Batch nr. 8: tensor([16, 17])
Batch nr. 9: tensor([18, 19])


In [31]:
from torch.utils.data import TensorDataset

In [35]:
t_x = torch.rand(5,3)
t_y = torch.randint(2,(5,1))

In [38]:
datas = TensorDataset(t_x,t_y)

In [37]:
data_l = DataLoader(datas)

for x,y in data_l:
    print(f"x = {x};  y = {y}")

x = tensor([[0.1902, 0.8041, 0.3415]]);  y = tensor([[0]])
x = tensor([[0.8256, 0.9132, 0.3833]]);  y = tensor([[0]])
x = tensor([[0.3079, 0.6710, 0.2495]]);  y = tensor([[0]])
x = tensor([[0.3630, 0.5540, 0.8255]]);  y = tensor([[0]])
x = tensor([[0.3911, 0.2913, 0.8452]]);  y = tensor([[1]])


In [41]:
data_l = DataLoader(datas,batch_size=2,shuffle=True)

for x,y in data_l:
    print(f"x = {x}; \ny = {y}")

x = tensor([[0.3630, 0.5540, 0.8255],
        [0.3911, 0.2913, 0.8452]]); 
y = tensor([[0],
        [1]])
x = tensor([[0.1902, 0.8041, 0.3415],
        [0.3079, 0.6710, 0.2495]]); 
y = tensor([[0],
        [0]])
x = tensor([[0.8256, 0.9132, 0.3833]]); 
y = tensor([[0]])


In [42]:
for epoch in range(2):
    print(f"Epoch {epoch}")
    for x,y in data_l:
        print(f"x = {x}; \ny = {y}")

Epoch 0
x = tensor([[0.8256, 0.9132, 0.3833],
        [0.1902, 0.8041, 0.3415]]); 
y = tensor([[0],
        [0]])
x = tensor([[0.3079, 0.6710, 0.2495],
        [0.3630, 0.5540, 0.8255]]); 
y = tensor([[0],
        [0]])
x = tensor([[0.3911, 0.2913, 0.8452]]); 
y = tensor([[1]])
Epoch 1
x = tensor([[0.1902, 0.8041, 0.3415],
        [0.3079, 0.6710, 0.2495]]); 
y = tensor([[0],
        [0]])
x = tensor([[0.3911, 0.2913, 0.8452],
        [0.3630, 0.5540, 0.8255]]); 
y = tensor([[1],
        [0]])
x = tensor([[0.8256, 0.9132, 0.3833]]); 
y = tensor([[0]])
